In [ ]:
#Numpy means numerical python,which is used for mathematical and scientific computation.
#mean,variance,standard deviation,median,mode,percentile,quartile in sab ko caculate karne ke liye numpy use hota hai.
#It has a function for working in domain of linear algebra, fourier transform and matrices.

#Numpy uses less memory to store data.Numpy makes it easy to perform mathematical operations on arrays 
#and used for creation of n-dimensional arrays and finding element numpy array is easy.

#pip install numpy

In [8]:
#example of list
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]
print(l1+l2) #output=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# print(l1*l2) #error
print(l1*10) #output=l1 ko 10 times print kar dega

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
#But array me addition,multiply and caluculation easy ho jata h.
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(a+10) # output=[11 12 13 14 15]
print(b*10)  #output=[60 70 80 90 100]
print(a*b) #output=[ 6 14 24 36 50]
#Note:array me ek hi DataType ka data store hota h.

#array vs list
#array takes less memory
#array can handle direct mathematical calculation
#easier to add,delete element from array
#array me diffent size ka nested data nhi store kar sakte h,but list me store kar sakte h.
l1=[1,2,3,[4,5]] #output:  [1, 2, 3, [4, 5]]
print(l1)  
# a1=np.array([1,2,3,[4,5]]) #error

[11 12 13 14 15]
[ 60  70  80  90 100]
[ 6 14 24 36 50]
[1, 2, 3, [4, 5]]
